---
- name: Retrieve VM list
  hosts: localhost
  roles:
    - ospinventory
    
- name: Init Setup
  hosts: all
  roles: 
    - setup

- name: Postgresql
  hosts: appdbs
  roles:
    - postgres

- name: Apache
  hosts: apps
  roles:
    - tomcat
    - apache
    - htmlapp

- name: HAProxy
  hosts: frontends
  roles:
    - haproxy


