---
# tasks file for postgres
- name: install progress
  yum:
    name: postgresql-server

- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgresql at boot
  service:
    name: postgresql
    enabled: yes

- name: tell user to finish setting up postgres
  debug:
    msg: "Either uncomment the postgres setup or manually login and initialize"

- name: Check /var/lib/pgsql/data exists
  stat:
    path: /var/lib/pgsql/data
  register: pgsql_result

- name: initilize postgres
  command: postgresql-setup initdb
  when: pgsql_result.stat.exists == False

- name: initilize postgres some more
  command: chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started